
tls:
  certificates:
    - certFile: "/etc/ssl/_wildcard.dev.tripleperformance.fr.pem"
      keyFile: "/etc/ssl/_wildcard.dev.tripleperformance.fr-key.pem"
    - certFile: "/etc/ssl/dev.itinera.ag.pem"
      keyFile: "/etc/ssl/dev.itinera.ag-key.pem"


http:
  middlewares:
    geoblock-china:
      plugin:
        geoblock:
          silentStartUp: false
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: false
          logApiRequests: true
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 750                                 # optional
          cacheSize: 15
          forceMonthlyUpdate: true
          allowUnknownCountries: true
          blackListMode: true
          unknownCountryApiResponse: "nil"
          countries:
            - CN